### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by Mazattack1999** [Mazattack1999/meditation-buddy#1]
- [x] Each group member creates a wireframe.
- [x] Compare wireframes and choose which one will be used.

**Comment by Mazattack1999** [comment]
Here is a link to my wireframe. 

https://wireframe.cc/XkBcMJ

**Comment by jrrangai** [comment]
![meditation_dailyDose](https://user-images.githubusercontent.com/99766422/162332591-90b79a13-8309-4011-8dd4-a247d028ceea.png)
![meditation_home](https://user-images.githubusercontent.com/99766422/162332592-5be808d9-c05a-4c3b-9157-ab0ae72baa08.png)
![meditation_about](https://user-images.githubusercontent.com/99766422/162332594-6cc0a405-d4b4-4811-967b-c08cdafac56f.png)
![meditation_tnt](https://user-images.githubusercontent.com/99766422/162332596-45bf44d6-aee6-430e-8d3e-9e98fed39f5f.png)
